# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7639ad78c7bef681631f015ccb1a10353c0fa2ac7cb120fc540187b28648ab4f7a16c84748fec49bbdca9d1deb7988c5571362ba26bd68aca3341178cb303111

test:
  secret_key_base: 20ae330da1bd9faefa9a88cbdb1002c804318a46605e400c23d6e020b1d43d0922aabf9b8bdb3110e22ec0640187301beaa4ecde6da05aed8d11f80830722198

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
