# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b6a4fdfa434e70cb572b65ce5d65113f22142fbdd3c8f5f2092c1338cb67b2269cdda2a2d36c74b4a4f2944269d1f202b39336e61e378918be8cb879226ceda

test:
  secret_key_base: 5d4d977265dcb2341b2060ccfbc39bcaedb1842d7dcb5e37ec9ba22e180196b3a861e592a3ec31e0bae56ddcd9419164e6ffd580a61c77adf084da6aea3955a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
